exclude: 'docs/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    - id: mypy
